ktor:
  deployment:
    port: ${APP_PORT:-8080}
    host: ${APP_HOST:-0.0.0.0}

  application:
    modules:
      - org.delcom.ApplicationKt.module

  # Konfigurasi Database (Digunakan di configureDatabases)
  database:
    # Pakai :-db agar kalau di server dia otomatis nyari container bernama 'db'
    host: ${DB_HOST:-db}
    port: ${DB_PORT:-5432}
    name: ${DB_NAME:-db_pam_proyek1}
    user: ${DB_USER:-postgres}
    password: ${DB_PASSWORD:-postgres}

  # Konfigurasi JWT
  jwt:
    # Ganti secret ini kalau mau lebih aman, tapi samakan dengan di .env
    secret: ${JWT_SECRET:-rahasia_grace_123_abc}
    issuer: ${JWT_ISSUER:-"http://0.0.0.0:8080/"}
    audience: ${JWT_AUDIENCE:-"http://0.0.0.0:8080/"}
    realm: ${JWT_REALM:-"Access to the wardrobe"}