ktor:
  application:
    modules:
      - org.delcom.ApplicationKt.module
  deployment:
    # Pakai 8080 sebagai default karena Nginx kamu nembak ke sini
    port: ${APP_PORT:-8080}
    host: ${APP_HOST:-0.0.0.0}

  database:
    # Pakai 'db' sebagai default karena ini standar Docker di Lab
    host: ${DB_HOST:-db}
    port: ${DB_PORT:-5432}
    name: ${DB_NAME:-db_pam_proyek1}
    user: ${DB_USER:-postgres}
    password: ${DB_PASSWORD:-postgres}

  jwt:
    secret: ${JWT_SECRET:-"rahasia_grace_123_abc"}

  app:
    # URL server kamu
    baseUrl: ${APP_URL:-"https://pam-2026-ifs23046-proyek1-be.s1if.life/"}